spring:
  application:
    name: Book_Authentication
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@bookservice.kgftc.mongodb.net/?retryWrites=true&w=majority&appName=BookService
      database: bookauthentication
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 5961
eureka:
  client:
    serviceUrl:
      defaultZone: http://book_eureka:8761/eureka/